# oss configurations
profiles:
  prof1:
    auth_key:
    auth_key_secret:
    endpoint:
    default_bucket:

  prof2:
    auth_key:
    auth_key_secret:
    endpoint:
    default_bucket:

proxies:
  #  http: http://qiyzh:FIbo1123@dl-proxy.neusoft.com:8080
  #  https: http://qiyzh:FIbo1123@dl-proxy.neusoft.com:8080
  http:
  https: